### ISSUE TITLE
Misnamed files

### ISSUE THREAD

**Issue by lenzjo** [adamgreen/pololu-3pi-plus-2040-arduino-library#1]
Hi,
Both Pololu3piPlus2040LEDs.h and Pololu3piPlus2040LEDs.cpp in the src dir have incorrect capitalization (both had "3Pi" and in one case "PLus"). Also in Pololu3piPlus2040LEDs.cpp the #include has the incorrect capitalization.

**Comment by adamgreen** [comment]
Good catch! Are you able to create a PR with your fixes? If not I will make the requested changes.

**Comment by lenzjo** [comment]
Hi Adam,

Sorry I don't know how to do that...

BFN, Clive

**Comment by adamgreen** [comment]
I just pushed up version 0.1.4 which should contain the fixes. Can you download and check to see if I got everything?

**Comment by lenzjo** [comment]
I can do that in the morning, will email you with the result.

**Comment by adamgreen** [comment]
> I can do that in the morning, will email you with the result.

Sounds like a plan!

**Comment by lenzjo** [comment]
Looks good. Compiled the "Demo" example... no problem.

**Comment by adamgreen** [comment]
> Looks good. Compiled the "Demo" example... no problem.

Excellent! Thanks for reporting and testing.

I will close this issue as completed.
